# List


In [4]:
x=[1,2,3,4,5]
print(x)
type(x)


[1, 2, 3, 4, 5]


list

In [14]:
x=[1,2,3,4,5,"english",True,1,2.4]
print(x[5])
print(len(x))
x.append(68)
print(x)
y=[0,1,2,3,4]
print(x+y)

english
9
[1, 2, 3, 4, 5, 'english', True, 1, 2.4, 68]
[1, 2, 3, 4, 5, 'english', True, 1, 2.4, 68, 0, 1, 2, 3, 4]


# Tuple

In [3]:
#Tuple used frist bracket and it is immutabel
tuple_1=(1,2,3,4,5)
print(tuple_1)
type(tuple_1)

(1, 2, 3, 4, 5)


tuple

In [6]:
#tuple used multiple type data at a time
tuple_2=(1,2,3,4,"Machine Learning",True)
print(tuple_2)

(1, 2, 3, 4, 'Machine Learning', True)


In [7]:
#conversion list to tuple
my_list=[1,2,3,4,"english"]
print(my_list)
my_tuple=tuple(my_list)
print(my_tuple)

[1, 2, 3, 4, 'english']
(1, 2, 3, 4, 'english')



my_tuple=("wood apple","mango","lady fingure")
my_list=list(my_tuple)
print(my_list)

In [9]:
#As it is immuateble so we can not chagne the value that means we can not added any value

# Set

In [13]:
#set used for carly bracket and set don't show redandent value
my_set={2,2,3,4,5}
print(my_set)
type(my_set)
my_set.add(20)
print()

{2, 3, 4, 5}
{2, 3, 4, 5, 20}


# Dictionary

In [14]:
#It is used like js object you can access it any way

In [19]:
my_dictionary={'name':'Rakibul','age':24,'country':'Bangladesh'}
print(my_dictionary);
print(my_dictionary["age"])

{'name': 'Rakibul', 'age': 24, 'country': 'Bangladesh'}
24


In [20]:
#dictionary aslo don't support redundent value


# import numpy as np


In [ ]:
#import nu
from time import process_time

In [22]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list =[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0


In [24]:
#Numpy Array
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [25]:
#create 1d array 
a=np.array([1,2,3,4])
a.shape

(4,)

In [36]:
#create 2d array using numphy
b= np.array([(1,2,3,4),(2,3,4,5)])
print(b)
b.shape

[[1 2 3 4]
 [2 3 4 5]]


(2, 4)

In [40]:
#creating a numpy array of zeros
c=np.zeros((4,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
#create an iddentity matrix
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[1 6 4]
 [9 3 5]
 [7 1 5]]
[[13 15 13]
 [14 12 19]
 [14 13 19]]
[[14 21 17]
 [23 15 24]
 [21 14 24]]
[[-12  -9  -9]
 [ -5  -9 -14]
 [ -7 -12 -14]]
[[ 13  90  52]
 [126  36  95]
 [ 98  13  95]]
[[0.07692308 0.4        0.30769231]
 [0.64285714 0.25       0.26315789]
 [0.5        0.07692308 0.26315789]]


In [48]:
#transpose
trans=np.transpose(a)
print(a)
print(trans)
print(trans.shape)
print(np.multiply(a,trans))

[[1 6 4]
 [9 3 5]
 [7 1 5]]
[[1 9 7]
 [6 3 1]
 [4 5 5]]
(3, 3)
[[ 1 54 28]
 [54  9  5]
 [28  5 25]]
